name: Deploy to Production with Workload Identity Federation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v0.4.0
      with:
        workload_identity_provider: projects/72746050019/locations/global/workloadIdentityPools/github/providers/live
        service_account: 72746050019-compute@developer.gserviceaccount.com

    - name: Terraform Init and Apply
      run: |
        cd prod/services/scheduler
        terraform init
        terraform apply -auto-approve