name: Deploy prod scheduler

on:
  push:
    branches:
      - main
    paths:
      - 'prod/services/scheduler/**'
  workflow_dispatch:

env:
  TF_VAR_url: ${{ vars.URL }}
  TF_VAR_region: ${{ vars.REGION }}
  TF_VAR_service_name: ${{ vars.SERVICE_NAME }}
  TF_VAR_scheduler_name: ${{ vars.SCHEDULER_NAME }}
  TF_VAR_project_id: ${{ vars.PROJECT_ID }}
  TF_VAR_access_key_id: ${{ secrets.ACCESS_KEY_ID }}
  TF_VAR_access_key_value: ${{ secrets.ACCESS_KEY_VALUE }}
  TF_VAR_atlas_user_id: ${{ secrets.ATLAS_USER_ID }}
  TF_VAR_atlas_user_value: ${{ secrets.ATLAS_USER_NAME }}
  TF_VAR_atlas_password_id: ${{ secrets.ATLAS_PASSWORD_ID }}
  TF_VAR_atlas_password_value: ${{ secrets.ATLAS_PASSWORD }}
  TF_VAR_atlas_connection_string_id: ${{ secrets.ATLAS_CONNECTION_STRING_ID }}
  TF_VAR_atlas_connection_string_value: ${{ secrets.ATLAS_CONNECTION_STRING_VALUE }}
  TF_VAR_connector_name: ${{ vars.CONNECTOR_NAME }}
  TF_VAR_cidr_range: ${{ vars.CIDR_RANGE }}
  TF_VAR_router_name: ${{ vars.ROUTER_NAME }}
  TF_VAR_ip_name: ${{ vars.IP_NAME }}

jobs:
  # setup:
  #   environment:
  #     name: prod
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4
  #     with:
  #       path: 'repo'

  #   - name: Upload repo
  #     uses: actions/upload-artifact@v2
  #     with:
  #       name: repo
  #       path: repo

  deploy_scheduler_with_data_puller:
    # needs: setup
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    environment:
      name: prod

    # steps:
    # - name: Download repo
    #   uses: actions/download-artifact@v2
    #   with:
    #     name: repo
    #     path: .
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        path: 'repo'

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v0.4.0
      with:
        workload_identity_provider: projects/72746050019/locations/global/workloadIdentityPools/github/providers/live
        service_account: github-actions@${{ vars.PROJECT_ID }}.iam.gserviceaccount.com
        project_id: ${{ vars.PROJECT_ID }}

    - name: Terraform init and apply for scheduler
      run: |
        cd repo/prod/services/scheduler
        terraform init
        terraform apply -auto-approve